apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          limits: # Limite máximo de recursos do container
            memory: 150Mi
            cpu: 150m # 1 core = 1000m (milicores) 200m = 20% do cpu. Posso utilizar também 0.5, 1, etc
          requests: # Quero que o kubernetes me garanta. Limite minimo
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM # O Redis usa essa variavel para se conectar ao master, no caso referenciamos o nome do service redis.
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
