apiVersion: v1
kind: Service # Tipo Serivice
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379 # Porta do container
    targetPort: 6379 # Porta exposta
  selector:
    app: redis # Seleciona o pod com o seletor app = redis
    role: master
    tier: backend
