apiVersion: v1
kind: Service
metadata:
  labels:
    app: meu-nginx
  name: meu-nginx
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: meu-nginx
  type: ClusterIP
status:
  loadBalancer: {}
