apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
spec:
  selector:
    matchLabels:
      app: app
      version: "1.0.0"
  replicas: 3
  template:
    metadata:
      labels:
        app: app
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: app
        image: linuxtips/nginx-prometheus-exporter:1.0.0
        env:
        - name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 80
        - containerPort: 32111
        resources: {}