apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    run: nginx
    track: stable
  name: app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32222       # Ngix
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - nodePort: 32111       # Prometheus
    name: prometheus
    port: 32111
    protocol: TCP
    targetPort: 32111
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer